# Generated by Django 5.1.4 on 2025-01-12 01:45

import django.db.models.deletion
import django_s3_storage.storage
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "video_file",
                    models.FileField(
                        storage=django_s3_storage.storage.S3Storage(
                            aws_s3_bucket_name="dc686f3b-6ffa3028-fd4d-4a79-8da7-0a7b31f7ff7f"
                        ),
                        upload_to=videos.models.videos_upload_to,
                    ),
                ),
                (
                    "video_cover_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django_s3_storage.storage.S3Storage(
                            aws_s3_bucket_name="dc686f3b-6ffa3028-fd4d-4a79-8da7-0a7b31f7ff7f"
                        ),
                        upload_to=videos.models.video_cover_upload_to,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
